# defaults - DWH
---
dwh:
  grpc_endpoint: "127.0.0.1:15050"
  http_endpoint: "127.0.0.1:15051"

  # or "https://sidechain-dev.sonm.com" to use remote node
  geth_url: "http://localhost:8545"

  enable_rest: true

  storage:
    driver: "postgres"
    endpoint: "postgresql://localhost:5432/dwh?user=dwh&password=dwh&sslmode=disable"
