# defaults - DWH
---
dwh:
  grpc_endpoint: "127.0.0.1:15050"
  http_endpoint: "127.0.0.1:15051"

  # or "https://sidechain-dev.sonm.com" to use remote node
  geth_url: "http://localhost:8545"

  enable_rest: true

  storage:
    driver: "postgres"
    dwh_user: "dwh"
    dwh_pass: "dwh"
    dwh_db: "dwh"
    endpoint: "postgresql://localhost:5432/{{ dwh_db }}?user={{ dwh_user }}&password={{ dwh_pass }}&sslmode=disable"
