- name: Set-up hosts
  hosts: vagrant
  become: true
  roles:
    - common
    - sonm-pkgcloud

- name: Install DWH
  hosts: vagrant
  become: true
  roles:
    - sonm-geth
    - sonm-dwh

- name: Install SONM Workers
  hosts: vagrant
  become: true
  vars:
    update_config: true
    update_keys: true
  roles:
    - ansible-docker
    - sonm-keys
    - sonm-worker

- name: Install SONM Client
  hosts: vagrant
  become: true
  vars:
    update_config: true
    update_keys: true
  roles:
    - sonm-keys
    - sonm-client
