- name: Set-up hosts
  hosts: common
  roles:
    - common
    - manage_ssh_keys

- name: Install SONM Locator
  hosts: locator
  become: true
  roles:
    - sonm-locator

- name: Install SONM Marker
  hosts: market
  become: true
  roles:
    - sonm-market

- name: Install SONM Hubs
  hosts: hubs
  become: true
  roles:
    - sonm-hub

- name: Install SONM Workers
  hosts: workers
  become: true
  roles:
    - ansible-docker
    - sonm-worker

- name: Install SONM Client
  hosts: client
  become: true
  roles:
    - sonm-client
