- name: (Re)Install SONM Locator
  hosts: locator
  become: true
  roles:
    - sonm-locator

- name: (Re)Install SONM Marker
  hosts: market
  become: true
  roles:
    - sonm-market

- name: (Re)Install SONM Hubs
  hosts: hubs
  become: true
  roles:
    - sonm-hub

- name: (Re)Install SONM Workers
  hosts: workers
  become: true
  roles:
    - sonm-worker

- name: (Re)Install SONM Client
  hosts: client
  become: true
  roles:
    - sonm-client
