- name: Download Node
  get_url:
    url: 'http://sonm-deb.home.nikonov.tech/sonm-node_0.2.1_amd64.deb'
    dest: '/tmp/sonm-node_0.2.1_amd64.deb'
    force: yes

- name: Download CLI
  get_url:
    url: 'http://sonm-deb.home.nikonov.tech/sonm-cli_0.2.1_amd64.deb'
    dest: '/tmp/sonm-cli_0.2.1_amd64.deb'
    force: yes

- name: Install Node
  command: dpkg --force-confdef --force-confold -i /tmp/sonm-node_0.2.1_amd64.deb

- name: Install CLI
  command: dpkg --force-confdef --force-confold -i /tmp/sonm-cli_0.2.1_amd64.deb

- name: Update Node config
  when: update_config is defined and update_config
  template:
    src: templates/node.yaml.j2
    dest: /etc/sonm/node-default.yaml
    backup: true
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  command: 'systemctl daemon-reload'
  notify:
    - Restart Node
