- name: install CLI and Node
  apt: cache_valid_time=3600 force=true state=present name={{ item }}
  with_items:
    - sonm-cli
    - sonm-node

- name: Update Node config
  when: update_config is defined and update_config
  template:
    src: templates/node.yaml.j2
    dest: /etc/sonm/node-default.yaml
    backup: true
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  command: 'systemctl daemon-reload'
  notify:
    - Restart Node
