- name: Download and install Node and CLI
  apt:
    deb: '{{ item }}'
    force: yes
  with_items:
    - 'http://sonm-deb.home.nikonov.tech/sonm-node_0.2.1_amd64.deb'
    - 'http://sonm-deb.home.nikonov.tech/sonm-cli_0.2.1_amd64.deb'

- name: Update Node config
  template:
    src=templates/node.yaml.j2
    dest=/etc/sonm/node-default.yaml
    owner=root
    group=root
    mode=0644
    force=yes

- name: Reload systemd daemon
  command: 'systemctl daemon-reload'
  notify:
    - Restart Node
