- name: Download Worker
  get_url:
    url: 'http://sonm-deb.home.nikonov.tech/sonm-miner_0.2.1_amd64.deb'
    dest: '/tmp/sonm-miner_0.2.1_amd64.deb'
    force: yes

- name: Install Worker
  command: dpkg --force-confdef --force-confold -i /tmp/sonm-miner_0.2.1_amd64.deb

- name: Update Worker config
  when: update_config is defined and update_config
  template:
    src: templates/worker.yaml.j2
    dest: /etc/sonm/miner-default.yaml
    backup: true
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  command: 'systemctl daemon-reload'
  notify:
    - Restart Worker
