- name: Download and install Worker
  apt:
    deb: 'http://sonm-deb.home.nikonov.tech/sonm-miner_0.2.1_amd64.deb'

- name: Update Worker config
  template:
    src=templates/worker.yaml.j2
    dest=/etc/sonm/miner-default.yaml
    owner=root
    group=root
    mode=0644
    force=yes

- name: Reload systemd daemon
  command: 'systemctl daemon-reload'
  notify:
    - Restart Worker
