ansible_host: 35.198.103.194
ansible_user: alex
ansible_ssh_private_key_file: ".keys/sshamna1101_gce"

# enable local hub management for this node
node_hub_addr: "127.0.0.1:10001"
worker_hub_addr: "7019bbf7FB8D51F9B71e82a878E1D9FD80c5421F@127.0.0.1:10002"
