- name: Download Marketplace
  get_url:
    url: 'http://sonm-deb.home.nikonov.tech/sonm-marketplace_0.2.1_amd64.deb'
    dest: '/tmp/sonm-marketplace_0.2.1_amd64.deb'
    force: yes

- name: Install Marketplace
  command: dpkg --force-confdef --force-confold -i /tmp/sonm-marketplace_0.2.1_amd64.deb

- name: Reload systemd daemon
  command: 'systemctl daemon-reload'
  notify:
    - Restart market
